### ISSUE TITLE
Guia blocks us upgrade compose from 1.4 to 1.5 due to removed AnimatedContentScope 

### ISSUE THREAD

**Issue by boy12hoody** [roudikk/guia#18]
First of all, the library is amazing and it suits our use cases well. My current issue is I am getting this error when I update compose dependencies to 1.5, compiler to 1.4.5. the app is compiling successfully but it crashes saying:
```
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/animation/AnimatedContentScope.
at com.roudikk.guia.containers.ScreenContainerKt$ScreenContainer$2.invoke(ScreenContainer.kt:25)
...
Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.compose.animation.AnimatedContentScope"
 ```

as they renamed [AnimatedContentScope to AnimatedContentTransitionScope](https://developer.android.com/jetpack/androidx/releases/compose-animation) in 1.5.

Can we have an update for compose 1.5?

**Comment by roudikk** [comment]
Hello, thank you! Seems like 1.5 is still in alpha currently, so I'm not sure about upgrading it cause most projects would be on the stable/rc version of Compose, but perhaps I can release an alpha version that you can use. Meanwhile, I'll do more investigation on the error and see if there's any way to solve it without upgrading.

**Comment by boy12hoody** [comment]
@roudikk thank you so much. And yes we are always on [compose alpha bom by Chris Banes](https://github.com/chrisbanes/compose-bom) cause our app is still in dev stage, we are trying to test/adopt latest things as much as possible. Hopefully we will be able to use Guia for long time as it's been considered better option for our multi module app.

**Comment by boy12hoody** [comment]
any update on this? @roudikk

**Comment by roudikk** [comment]
@boy12hoody Hey sorry for slow reply, I have been very sick actually for last few weeks and haven't been able to work on this much at all. If you're able to create a branch / PR of a suggested solution I'm all ears. Otherwise, I probably won't be able to get to this till next week :/

**Comment by boy12hoody** [comment]
> @boy12hoody Hey sorry for slow reply, I have been very sick actually for last few weeks and haven't been able to work on this much at all. If you're able to create a branch / PR of a suggested solution I'm all ears. Otherwise, I probably won't be able to get to this till next week :/

No problem.  Get well soon brother!
